spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23limeJicLm7IFogjG
            clientSecret: a27853040f001015a8a6e4903d4c9d8424a3195f
            scope: read:user
